from Queue import Queue

if __name__== "__main__":
    q = Queue(3)
    print(q)
    print("Size:",len(q))
    print("Empty?",q.isEmpty())
    front_e = q.dequeue()
    print(f"The element at the front was: {front_e}")
    q.enqueue(1)
    q.enqueue(2)
    q.enqueue(3)
    print("Size:",len(q))
    print(q)
    q.enqueue(4)
    print("Size:",len(q))
    print(q)
    q.dequeue()
    q.dequeue()
    print(q)
    q.enqueue(5)
    q.enqueue(6)
    q.enqueue(7)
    print("Size:",len(q))
    print(q)
    q.enqueue(8)
    print("Size:",len(q))
    print(q)
    q.enqueue(9)
    print("Size:",len(q))
    print(q)
    q.dequeue()
    q.dequeue()
    q.dequeue()
    q.dequeue()
    print("Size:",len(q))
    print(q)
    print("First element: ",q.peek())